data:
  cruise_pre.db: ../data/cruise_pre.db
  cruise_post.db: ../data/cruise_post.db

features:
  - Age
  - Online Check-in
  - Onboard Wifi Service

models:
  - RandomForestClassifier
  - LogisticRegression
  - GradientBoostingClassifier

hyperparameters:
  RandomForestClassifier:
    n_estimators: 200
    random_state: 42
    max_depth: 7
  LogisticRegression:
    C: 0.8
    penalty: l2
    max_iter: 700
    solver: 'sag'
  GradientBoostingClassifier:
    n_estimators: 200
    learning_rate: 0.2
    random_state: 42
