data:
  cruise_pre.db: ../data/cruise_pre.db
  cruise_post.db: ../data/cruise_post.db

features:
  - Age
  - Online Check-in
  - Onboard Wifi Service

models:
  - RandomForestClassifier
  - LogisticRegression
  - GradientBoostingClassifier

hyperparameters:
  RandomForestClassifier:
    n_estimators: 100
    random_state: 42
    max_depth: 5
  LogisticRegression:
    C: 1.0
    penalty: l2
    max_iter: 500
  GradientBoostingClassifier:
    n_estimators: 100
    learning_rate: 0.1
    random_state: 42
